### ISSUE TITLE
[MITOSIS MODIFIER] Enemies that spawn Blessed remain blessed even after all Idols are destroyed.

### ISSUE THREAD

**Issue by UntotenTheo** [wafflethings/UltraTweaker#2]
Issue was present in the now deprecated ULTRAKILLtweaker mod, though due to what I can only assume is some internal stuff changing, the issue is even worse now as you effectively get softlocked if you can't exit a room and/or cant clip out (Easily observable in 5-2: Waves of the Starless Sea)

This bug likely occurs because when an enemy spawns as Blessed, its properties including the Bless is copied over to its clone, and same happens for the Idol. However for whatever reason, the Idols only bless the original enemy, leaving the other invulnerable enemy without an Idol, yet still having immunity to most sources of damage.

This bug does **not** occur in the Cyber Grind, as enemies do not begin Blessed.

**Comment by wafflethings** [comment]
duplicated enemies have now been set to spawn unblessed. this should work

**Comment by UntotenTheo** [comment]
God bless you, great mod!
