### ISSUE TITLE
The original options menu is overlayed by the new menu.

### ISSUE THREAD

**Issue by lumithespoofy64** [wafflethings/UltraTweaker#23]
![20240304161026_1](https://github.com/wafflethings/UltraTweaker/assets/111160282/ab8fd53e-a9c3-486c-aea1-90b2ce881246)

You also cannot modify your old settings.

**Comment by cloudythoughts06** [comment]
I'm having this problem as well. It's a bit of a shame, since it's the only thing that's preventing me from using this mod.

**Comment by lumithespoofy64** [comment]
They fixed this in the latest update 👍
