### ISSUE TITLE
Mitosis has gotten better, however there are a couple of softlocks that still persist.

### ISSUE THREAD

**Issue by LilWheedle** [wafflethings/UltraTweaker#4]
Most softlocks due to the recent UltraTweaker update have been fixed. Hurray!
However there are some arenas that still experience softlocks where doors don't open, and arenas don't progress.
I didn't play much of act 1, but I can provide some instances in act 2 where it happened;
4-1,  5th arena in. After killing the first wave of enemies, it doesn't progress the arena, so the filths and virtues don't spawn.
6-1, Room with the maurices, virtures, and turrets. After killing all enemies, the door does not open.
P-2, Room where the idols are broken to expose mindflayers. After killing the swordsmachines and turrets, the arena doesn't progress.

**Comment by wafflethings** [comment]
this now works
