### ISSUE TITLE
[suggestion/notice] glass cannon modifier

### ISSUE THREAD

**Issue by x8c8r** [wafflethings/UltraTweaker#9]
in pre-thunderstore version there was a modifier that was called "glass cannon" (i think).

it capped your hp at 30 but doubled your damage. the fact that its not in the current version is kind of sad since it is fun to play with, so either consider adding a damage increase modifier or bring back glass cannon

**Comment by wafflethings** [comment]
it didnt increase damage, it halved enemy health. you can manually recreate it with fragility + tankify

**Comment by x8c8r** [comment]
> it didnt increase damage, it halved enemy health. you can manually recreate it with fragility + tankify

ah
